openapi: 3.0.3
info:
  title: SynergyAcademy
  description: SynergyAcademy
  version: 1.0.0
paths:
  /students:
    get:
      operationId: getAllStudents
      responses:
        200:
          description: OK
        500:
          description: error while getting all students
    post:
      operationId: addStudent
      responses:
        200:
          description: OK
        500:
          description: error while adding new student
  /students/{studentId}:
    get:
      operationId: getStudentById
      parameters:
        - in: path
          name: studentId
          required: true
          schema:
            type: integer
      responses:
        200:
          description: OK
        500:
          description: error while getting student by id
    put:
      operationId: updateStudentById
      parameters:
        - in: path
          name: studentId
          required: true
          schema:
            type: integer
      responses:
        200:
          description: OK
        500:
          description: error while updating student by id
  /courses:
    get:
      operationId: getAllCourses
      responses:
        200:
          description: OK
        500:
          description: error while getting all courses
    post:
      operationId: addCourse
      responses:
        200:
          description: OK
        500:
          description: error while adding new course
  /courses/{courseId}:
    get:
      operationId: getCourseById
      parameters:
        - in: path
          name: courseId
          required: true
          schema:
            type: integer
      responses:
        200:
          description: OK
        500:
          description: error while getting course by id
    put:
      operationId: updateCourseById
      parameters:
        - in: path
          name: courseId
          required: true
          schema:
            type: integer
      responses:
        200:
          description: OK
        500:
          description: error while updating course by id
  /courses/{courseId}/exams:
    get:
      operationId: getExamsByCourseId
      parameters:
        - in: path
          name: courseId
          required: true
          schema:
            type: integer
      responses:
        200:
          description: OK
        500:
          description: error while getting exams by course id
    post:
      operationId: addExam
      parameters:
        - in: path
          name: courseId
          required: true
          schema:
            type: integer
      responses:
        200:
          description: OK
        500:
          description: error while adding new exam
  /exams/{examId}:
    get:
      operationId: getExamById
      parameters:
        - in: path
          name: examId
          required: true
          schema:
            type: integer
      responses:
        200:
          description: OK
        500:
          description: error while getting exam by id
    put:
      operationId: updateExamById
      parameters:
        - in: path
          name: examId
          required: true
          schema:
            type: integer
      responses:
        200:
          description: OK
        500:
          description: error while updating exam by id
  /classifierservice/{tableName}:
    get:
      operationId: getClassifier
      parameters:
        - in: path
          name: tableName
          required: true
          schema:
            type: string
      responses:
        200:
          description: OK
        500:
          description: error while getting classifier
  /config/{type}:
    get:
      operationId: getConfig
      parameters:
        - in: path
          name: type
          required: true
          schema:
            type: string
      responses:
        200:
          description: OK
        500:
          description: error while getting config