openapi: 3.0.3
info:
  title: SynergyAcademy
  description: SynergyAcademy
  version: 1.0.0
paths:
  /students:
    get:
      operationId: getAllStudents
      responses:
        200:
          description: OK
        500:
          description: error while getting all students
  /courses:
    get:
      operationId: getAllCourses
      responses:
        200:
          description: OK
        500:
          description: error while getting all courses