openapi: 3.0.3
info:
  title: SynergyAcademy
  description: SynergyAcademy
  version: 1.0.0
paths:
  /students:
    get:
      operationId: getAllStudents
      description: Returns all students from all courses of all time
      responses:
        200:
          description: OK
        204:
          description: requested resource(students) returned empty response
        500:
          description: error while getting all students
    post:
      operationId: addStudent
      responses:
        200:
          description: OK
        500:
          description: error while adding new student
  /students/{studentId}:
    get:
      operationId: getStudentById
      parameters:
        - in: path
          name: studentId
          required: true
          schema:
            type: integer
      responses:
        200:
          description: OK
        500:
          description: error while getting student by id
    put:
      operationId: updateStudentById
      parameters:
        - in: path
          name: studentId
          required: true
          schema:
            type: integer
      responses:
        200:
          description: OK
        500:
          description: error while updating student by id
  /courses:
    get:
      operationId: getAllCourses
      responses:
        200:
          description: OK
        500:
          description: error while getting all courses
    post:
      operationId: addCourse
      responses:
        200:
          description: OK
        500:
          description: error while adding new course
  /courses/{courseId}:
    get:
      operationId: getCourseById
      parameters:
        - in: path
          name: courseId
          required: true
          schema:
            type: integer
      responses:
        200:
          description: OK
        500:
          description: error while getting course by id
    put:
      operationId: updateCourseById
      parameters:
        - in: path
          name: courseId
          required: true
          schema:
            type: integer
      responses:
        200:
          description: OK
        500:
          description: error while updating course by id
  /courses/{courseId}/exams:
    get:
      operationId: getExamsByCourseId
      parameters:
        - in: path
          name: courseId
          required: true
          schema:
            type: integer
      responses:
        200:
          description: OK
        500:
          description: error while getting exams by course id
    post:
      operationId: addExam
      parameters:
        - in: path
          name: courseId
          required: true
          schema:
            type: integer
      responses:
        200:
          description: OK
        500:
          description: error while adding new exam
  /courses/{courseId}/students:
    get:
      operationId: getStudentsByCourseId
      parameters:
        - in: path
          name: courseId
          required: true
          schema:
            type: integer
      responses:
        200:
          description: OK
        500:
          description: error while getting students by course id
  /courses/{courseId}/educationprocess:
    get:
      operationId: getEducationProcessByCourseId
      parameters:
        - in: path
          name: courseId
          required: true
          schema:
            type: integer
      responses:
        200:
          description: OK
        500:
          description: error while getting education process by course id
  /educationprocess/{educationProcessId}:
    get:
      operationId: getEducationProcessById
      parameters:
        - in: path
          name: educationProcessId
          required: true
          schema:
            type: integer
      responses:
        200:
          description: OK
        500:
          description: error while getting education process by id
  /educationprocess/{educationProcessId}/grades:
    get:
      operationId: getGradesByEducationProcessId
      parameters:
        - in: path
          name: educationProcessId
          required: true
          schema:
            type: integer
      responses:
        200:
          description: OK
        500:
          description: error while getting grades by education process id
  /exams/{examId}:
    get:
      operationId: getExamById
      parameters:
        - in: path
          name: examId
          required: true
          schema:
            type: integer
      responses:
        200:
          description: OK
        500:
          description: error while getting exam by id
    put:
      operationId: updateExamById
      parameters:
        - in: path
          name: examId
          required: true
          schema:
            type: integer
      responses:
        200:
          description: OK
        500:
          description: error while updating exam by id
  /exams/{examId}/students:
    get:
      operationId: getStudentsByExamId
      parameters:
        - in: path
          name: examId
          required: true
          schema:
            type: integer
      responses:
        200:
          description: OK
        500:
          description: error while getting students by exam id
  /exams/{examId}/results:
    get:
      operationId: getResultsByExamId
      parameters:
        - in: path
          name: examId
          required: true
          schema:
            type: integer
      responses:
        200:
          description: OK
        500:
          description: error while getting results by exam id
    put:
      operationId: updateResults
      parameters:
        - in: path
          name: examId
          required: true
          schema:
            type: integer
      responses:
        200:
          description: OK
        500:
          description: error while updating results
  /email:
    post:
      operationId: sendInvitationLink
      responses:
        200:
          description: OK
        500:
          description: error while sending invitation link
  /reports/pieChart:
    get:
      operationId: getReportsPieChart
      responses:
        200:
          description: OK
        500:
          description: error while getting pie chart report
  /reports/tableReport:
    get:
      operationId: getReportsTable
      responses:
        200:
          description: OK
        500:
          description: error while getting table report
  /reports/columnChart:
    get:
      operationId: getReportsColumnChart
      responses:
        200:
          description: OK
        500:
          description: error while getting column chart report
  /reports/histogram:
    get:
      operationId: getReportsHistogram
      responses:
        200:
          description: OK
        500:
          description: error while getting histogram report
  /classifierservice/{tableName}:
    get:
      operationId: getClassifier
      parameters:
        - in: path
          name: tableName
          required: true
          schema:
            type: string
      responses:
        200:
          description: OK
        500:
          description: error while getting classifier

  /config/{type}:
    get:
      operationId: getConfig
      parameters:
        - in: path
          name: type
          required: true
          schema:
            type: string
      responses:
        200:
          description: OK
        500:
          description: error while getting config